# Generated by Django 2.2.4 on 2019-09-05 14:01

import datetime
from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('operator_fname', models.CharField(max_length=50)),
                ('operator_lname', models.CharField(max_length=50)),
                ('operator_email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('operator_pass', models.CharField(max_length=50)),
                ('operator_mobile', models.IntegerField()),
                ('operator_address', models.CharField(max_length=300)),
                ('operator_city', models.CharField(max_length=50)),
                ('operator_pin', models.IntegerField()),
                ('operator_state', models.CharField(max_length=30)),
                ('operator_country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(default=datetime.datetime(2019, 9, 5, 19, 31, 37, 535884), max_length=50, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('subcategory', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('desc', models.CharField(default='', max_length=300)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(default='2', upload_to=shop.models.products_path)),
            ],
        ),
        migrations.CreateModel(
            name='Product_request',
            fields=[
                ('request_id', models.CharField(default=datetime.datetime(2019, 9, 5, 19, 31, 37, 535884), max_length=50, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('subcategory', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=300)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(upload_to=shop.models.request_path)),
                ('vendor_firmname', models.CharField(max_length=200)),
                ('vendor_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Pulled_requests',
            fields=[
                ('product_id', models.CharField(default=datetime.datetime(2019, 9, 5, 19, 31, 37, 535884), max_length=50, primary_key=True, serialize=False)),
                ('oldproduct_name', models.CharField(max_length=200)),
                ('newproduct_name', models.CharField(max_length=200)),
                ('oldcategory', models.CharField(max_length=50)),
                ('newcategory', models.CharField(max_length=50)),
                ('old_subcategory', models.CharField(max_length=50)),
                ('new_subcategory', models.CharField(max_length=50)),
                ('olddesc', models.CharField(max_length=300)),
                ('newdesc', models.CharField(max_length=300)),
                ('request_date', models.CharField(max_length=20)),
                ('pulled_date', models.CharField(max_length=20)),
                ('requestedby_vendor', models.CharField(max_length=200)),
                ('requestedby_email', models.EmailField(max_length=254)),
                ('pulledby_operator', models.CharField(max_length=200)),
                ('pulledby_email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to=shop.models.products_path)),
                ('oldprice', models.IntegerField(default=0)),
                ('newprice', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('cust_fname', models.CharField(max_length=50)),
                ('cust_lname', models.CharField(max_length=50)),
                ('cust_dob', models.CharField(max_length=10)),
                ('cust_email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('cust_pass', models.CharField(max_length=50)),
                ('cust_mobile', models.IntegerField()),
                ('cust_gender', models.CharField(max_length=10)),
                ('cust_address', models.CharField(max_length=300)),
                ('cust_city', models.CharField(max_length=50)),
                ('cust_pin', models.IntegerField()),
                ('cust_state', models.CharField(max_length=30)),
                ('cust_country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_firmname', models.CharField(max_length=200)),
                ('vendor_owner', models.CharField(max_length=50)),
                ('vendor_email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('vendor_pass', models.CharField(max_length=50)),
                ('vendor_mobile', models.IntegerField()),
                ('vendor_address', models.CharField(max_length=300)),
                ('vendor_city', models.CharField(max_length=50)),
                ('vendor_pin', models.IntegerField()),
                ('vendor_state', models.CharField(max_length=30)),
                ('vendor_country', models.CharField(max_length=30)),
            ],
        ),
    ]
