# Generated by Django 2.2.4 on 2019-09-05 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=datetime.datetime(2019, 9, 5, 19, 31, 46, 616925), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product_request',
            name='request_id',
            field=models.CharField(default=datetime.datetime(2019, 9, 5, 19, 31, 46, 616925), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pulled_requests',
            name='product_id',
            field=models.CharField(default=datetime.datetime(2019, 9, 5, 19, 31, 46, 616925), max_length=50, primary_key=True, serialize=False),
        ),
    ]
