# Generated by Django 2.2.4 on 2019-09-10 08:47

import datetime
from django.db import migrations, models
import django.utils.timezone
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190905_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulled_requests',
            name='old_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=shop.models.pulledreq_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=datetime.datetime(2019, 9, 10, 14, 16, 49, 828176), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product_request',
            name='request_id',
            field=models.CharField(default=datetime.datetime(2019, 9, 10, 14, 16, 49, 828176), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pulled_requests',
            name='product_id',
            field=models.CharField(default=datetime.datetime(2019, 9, 10, 14, 16, 49, 828176), max_length=50, primary_key=True, serialize=False),
        ),
    ]
