# Generated by Django 2.2.4 on 2019-09-10 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190910_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pulled_requests',
            name='old_image',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=datetime.datetime(2019, 9, 10, 19, 17, 14, 468532), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product_request',
            name='request_id',
            field=models.CharField(default=datetime.datetime(2019, 9, 10, 19, 17, 14, 468532), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pulled_requests',
            name='product_id',
            field=models.CharField(default=datetime.datetime(2019, 9, 10, 19, 17, 14, 468532), max_length=50, primary_key=True, serialize=False),
        ),
    ]
